### ISSUE TITLE
Release for Scala 2.12

### ISSUE THREAD

**Issue by ScalaWilliam** [maffoo/jsonquote#5]
Scala 2.12 has been out a while.

**Comment by maffoo** [comment]
I added support for scala 2.12 in the branch [`scala-2.12`](https://github.com/maffoo/jsonquote/tree/scala-2.12) ([travis](https://travis-ci.org/maffoo/jsonquote/builds/203691223)), including the needed library upgrades. Unfortunately there is no final release of play-json for scala 2.12; the latest is `2.6.0-M3`. I am thinking about bumping the version to 0.5.0 for 2.12 support, so I could either release 0.5.0 now with the milestone dependency for play-json, or else release a milestone version of jsonquote now and then a final version when play 2.6 is out. Thoughts?

**Comment by ScalaWilliam** [comment]
For 2.12 release against 2.6.0-M3 and for 2.11 as now. play-json is independently versioned from play from 2.6

**Comment by maffoo** [comment]
Version 0.5.0 has been published with support for scala 2.10, 2.11, and 2.12.
